// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnp75rTre2FvVW13eBDIT23DIbZ8LnzNM',
    appId: '1:466687791773:web:e08702a977b979cab93a74',
    messagingSenderId: '466687791773',
    projectId: 'shibringo-8bd93',
    authDomain: 'shibringo-8bd93.firebaseapp.com',
    storageBucket: 'shibringo-8bd93.appspot.com',
    measurementId: 'G-5491V8P2VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFdqRpOgIYxNO40zmQvCHH8hn1G6N1wIo',
    appId: '1:466687791773:android:0330c57b01c48a19b93a74',
    messagingSenderId: '466687791773',
    projectId: 'shibringo-8bd93',
    storageBucket: 'shibringo-8bd93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDopbFEONBSd15zCbD0TGZSLV1E_aXkZA8',
    appId: '1:466687791773:ios:6fd51273b9111990b93a74',
    messagingSenderId: '466687791773',
    projectId: 'shibringo-8bd93',
    storageBucket: 'shibringo-8bd93.appspot.com',
    iosBundleId: 'com.example.shibringo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDopbFEONBSd15zCbD0TGZSLV1E_aXkZA8',
    appId: '1:466687791773:ios:befe61deb730b610b93a74',
    messagingSenderId: '466687791773',
    projectId: 'shibringo-8bd93',
    storageBucket: 'shibringo-8bd93.appspot.com',
    iosBundleId: 'com.example.shibringo.RunnerTests',
  );
}
